services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: food_nutrition_db
    environment:
      POSTGRES_DB: food_nutrition_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - food_network

  # pgAdmin (Optional - for database management GUI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@food-nutrition.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - food_network

  # Streamlit Application
  streamlit:
    build:
      context: ..
      dockerfile: streamlit_app/Dockerfile
    container_name: food_nutrition_streamlit
    volumes:
      - ../streamlit_app:/app
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=food_nutrition_db
      - DB_PORT=5432
      - DB_NAME=food_nutrition_db
      - DB_USER=analyst_user
      - DB_PASSWORD=analyst_password
    depends_on:
      - postgres
    networks:
      - food_network
volumes:
  postgres_data:


networks:
  food_network:
    driver: bridge
